/*
 * Copyright 2024 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.mobilestartup.services
import cats.implicits._
import com.google.inject.name.Named
import javax.inject.Inject
import uk.gov.hmrc.mobilestartup.connectors.GenericConnector

import scala.concurrent.{ExecutionContext, Future}

class LiveStartupService @Inject() (
  connector:                                                                                         GenericConnector[Future],
  @Named("feature.userPanelSignUp") userPanelSignUp:                                                 Boolean,
  @Named("feature.enablePushNotificationTokenRegistration") enablePushNotificationTokenRegistration: Boolean,
  @Named("feature.paperlessAlertDialogs") enablePaperlessAlertDialogs:                               Boolean,
  @Named("feature.paperlessAdverts") enablePaperlessAdverts:                                         Boolean,
  @Named("feature.htsAdverts") enableHtsAdverts:                                                     Boolean,
  @Named("feature.annualTaxSummaryLink") enableAnnualTaxSummaryLink:                                 Boolean,
  @Named("cbProofOfEntitlementUrl") cbProofOfEntitlementUrl:                                         Option[String],
  @Named("cbProofOfEntitlementUrlCy") cbProofOfEntitlementUrlCy:                                     Option[String],
  @Named("cbPaymentHistoryUrl") cbPaymentHistoryUrl:                                                 Option[String],
  @Named("cbPaymentHistoryUrlCy") cbPaymentHistoryUrlCy:                                             Option[String],
  @Named("cbChangeBankAccountUrl") cbChangeBankAccountUrl:                                           Option[String],
  @Named("cbChangeBankAccountUrlCy") cbChangeBankAccountUrlCy:                                       Option[String],
  @Named("cbHomeUrl") cbHomeUrl:                                                                     Option[String],
  @Named("cbHomeUrlCy") cbHomeUrlCy:                                                                 Option[String],
  @Named("cbHowToClaimUrl") cbHowToClaimUrl:                                                         Option[String],
  @Named("cbHowToClaimUrlCy") cbHowToClaimUrlCy:                                                     Option[String],
  @Named("cbFullTimeEducationUrl") cbFullTimeEducationUrl:                                           Option[String],
  @Named("cbFullTimeEducationUrlCy") cbFullTimeEducationUrlCy:                                       Option[String],
  @Named("cbWhatChangesUrl") cbWhatChangesUrl:                                                       Option[String],
  @Named("cbWhatChangesUrlCy") cbWhatChangesUrlCy:                                                   Option[String],
  @Named("statePensionUrl") statePensionUrl:                                                         Option[String],
  @Named("niSummaryUrl") niSummaryUrl:                                                               Option[String],
  @Named("niContributionsUrl") niContributionsUrl:                                                   Option[String],
  @Named("otherTaxesDigitalAssistantUrl") otherTaxesDigitalAssistantUrl:                             Option[String],
  @Named("otherTaxesDigitalAssistantUrlCy") otherTaxesDigitalAssistantUrlCy:                         Option[String],
  @Named("payeDigitalAssistantUrl") payeDigitalAssistantUrl:                                         Option[String],
  @Named("payeDigitalAssistantUrlCy") payeDigitalAssistantUrlCy:                                     Option[String],
  @Named("incomeTaxGeneralEnquiriesUrl") incomeTaxGeneralEnquiriesUrl:                               Option[String],
  @Named("incomeTaxGeneralEnquiriesUrlCy") incomeTaxGeneralEnquiriesUrlCy:                           Option[String],
  @Named("learnAboutCallChargesUrl") learnAboutCallChargesUrl:                                       Option[String],
  @Named("learnAboutCallChargesUrlCy") learnAboutCallChargesUrlCy:                                   Option[String],
  @Named("statePensionAgeUrl") statePensionAgeUrl:                                                   Option[String],
  @Named("tcNationalInsuranceRatesLettersUrl") tcNationalInsuranceRatesLettersUrl:                   Option[String],
  @Named("tcNationalInsuranceRatesLettersUrlCy") tcNationalInsuranceRatesLettersUrlCy:               Option[String],
  @Named("tcPersonalAllowanceUrl") tcPersonalAllowanceUrl:                                           Option[String],
  @Named("tcPersonalAllowanceUrlCy") tcPersonalAllowanceUrlCy:                                       Option[String],
  @Named("scottishIncomeTaxUrl") scottishIncomeTaxUrl:                                               Option[String],
  @Named("scottishIncomeTaxUrlCy") scottishIncomeTaxUrlCy:                                           Option[String],
  @Named("cbTaxChargeUrl") cbTaxChargeUrl:                                                           Option[String],
  @Named("cbTaxChargeUrlCy") cbTaxChargeUrlCy:                                                       Option[String],
  @Named("selfAssessmentHelpAppealingPenaltiesUrl") selfAssessmentHelpAppealingPenaltiesUrl:         Option[String],
  @Named("selfAssessmentHelpAppealingPenaltiesUrlCy") selfAssessmentHelpAppealingPenaltiesUrlCy:     Option[String],
  @Named("addMissingTaxableIncomeUrl") addMissingTaxableIncomeUrl:                                   Option[String],
  @Named("helpToSaveGeneralEnquiriesUrl") helpToSaveGeneralEnquiriesUrl:                             Option[String],
  @Named("helpToSaveGeneralEnquiriesUrlCy") helpToSaveGeneralEnquiriesUrlCy:                         Option[String],
  @Named("helpToSaveDigitalAssistantUrl") helpToSaveDigitalAssistantUrl:                             Option[String],
  @Named("selfAssessmentGeneralEnquiriesUrl") selfAssessmentGeneralEnquiriesUrl:                     Option[String],
  @Named("selfAssessmentGeneralEnquiriesUrlCy") selfAssessmentGeneralEnquiriesUrlCy:                 Option[String],
  @Named("simpleAssessmentGeneralEnquiriesUrl") simpleAssessmentGeneralEnquiriesUrl:                 Option[String],
  @Named("simpleAssessmentGeneralEnquiriesUrlCy") simpleAssessmentGeneralEnquiriesUrlCy:             Option[String],
  @Named("cbGeneralEnquiriesUrl") cbGeneralEnquiriesUrl:                                             Option[String],
  @Named("cbGeneralEnquiriesUrlCy") cbGeneralEnquiriesUrlCy:                                         Option[String],
  @Named("taxCreditsGeneralEnquiriesUrl") taxCreditsGeneralEnquiriesUrl:                             Option[String],
  @Named("taxCreditsGeneralEnquiriesUrlCy") taxCreditsGeneralEnquiriesUrlCy:                         Option[String],
  @Named("otherTaxesGeneralEnquiriesUrl") otherTaxesGeneralEnquiriesUrl:                             Option[String],
  @Named("otherTaxesGeneralEnquiriesUrlCy") otherTaxesGeneralEnquiriesUrlCy:                         Option[String],
  @Named("findRepaymentPlanUrl") findRepaymentPlanUrl:                                               Option[String],
  @Named("findRepaymentPlanUrlCy") findRepaymentPlanUrlCy:                                           Option[String],
  @Named("pensionAnnualAllowanceUrl") pensionAnnualAllowanceUrl:                                     Option[String],
  @Named("pensionAnnualAllowanceUrlCy") pensionAnnualAllowanceUrlCy:                                 Option[String],
  @Named("childBenefitDigitalAssistantUrl") childBenefitDigitalAssistantUrl:                         Option[String],
  @Named("childBenefitDigitalAssistantUrlCy") childBenefitDigitalAssistantUrlCy:                     Option[String],
  @Named("incomeTaxDigitalAssistantUrl") incomeTaxDigitalAssistantUrl:                               Option[String],
  @Named("incomeTaxDigitalAssistantUrlCy") incomeTaxDigitalAssistantUrlCy:                           Option[String],
  @Named("selfAssessmentDigitalAssistantUrl") selfAssessmentDigitalAssistantUrl:                     Option[String],
  @Named("selfAssessmentDigitalAssistantUrlCy") selfAssessmentDigitalAssistantUrlCy:                 Option[String],
  @Named("taxCreditsDigitalAssistantUrl") taxCreditsDigitalAssistantUrl:                             Option[String],
  @Named("taxCreditsDigitalAssistantUrlCy") taxCreditsDigitalAssistantUrlCy:                         Option[String],
  @Named("tcStateBenefitsUrl") tcStateBenefitsUrl:                                                   Option[String],
  @Named("tcStateBenefitsUrlCy") tcStateBenefitsUrlCy:                                               Option[String],
  @Named("tcCompanyBenefitsUrl") tcCompanyBenefitsUrl:                                               Option[String],
  @Named("tcCompanyBenefitsUrlCy") tcCompanyBenefitsUrlCy:                                           Option[String],
  @Named("niAppleWalletUrl") niAppleWalletUrl:                                                       Option[String],
  @Named("niGoogleWalletUrl") niGoogleWalletUrl:                                                     Option[String],
  @Named("feature.customerSatisfactionSurveys") enableCustomerSatisfactionSurveys:                   Boolean,
  @Named("feature.findMyNinoAddToWallet") findMyNinoAddToWallet:                                     Boolean,
  @Named("feature.disableYourEmploymentIncomeChart") disableYourEmploymentIncomeChart:               Boolean,
  @Named("feature.disableYourEmploymentIncomeChartAndroid") disableYourEmploymentIncomeChartAndroid: Boolean,
  @Named("feature.disableYourEmploymentIncomeChartIos") disableYourEmploymentIncomeChartIos:         Boolean,
  @Named("feature.findMyNinoAddToGoogleWallet") findMyNinoAddToGoogleWallet:                         Boolean,
  @Named("feature.disableOldTaxCalculator") disableOldTaxCalculator:                                 Boolean,
  @Named("feature.useNudgeComm") useNudgeComm:                                                       Boolean,
  @Named("feature.enableChangeOfBankPegaURL") enableChangeOfBankPegaURL:                             Boolean,
  @Named("feature.enableTaxCreditEndBanner") enableTaxCreditEndBanner:                               Boolean
)(implicit ec:                                                                                       ExecutionContext)
    extends StartupServiceImpl[Future](connector,
                                       userPanelSignUp,
                                       enablePushNotificationTokenRegistration,
                                       enablePaperlessAlertDialogs,
                                       enablePaperlessAdverts,
                                       enableHtsAdverts,
                                       enableAnnualTaxSummaryLink,
                                       cbProofOfEntitlementUrl,
                                       cbProofOfEntitlementUrlCy,
                                       cbPaymentHistoryUrl,
                                       cbPaymentHistoryUrlCy,
                                       cbChangeBankAccountUrl,
                                       cbChangeBankAccountUrlCy,
                                       cbHomeUrl,
                                       cbHomeUrlCy,
                                       cbHowToClaimUrl,
                                       cbHowToClaimUrlCy,
                                       cbFullTimeEducationUrl,
                                       cbFullTimeEducationUrlCy,
                                       cbWhatChangesUrl,
                                       cbWhatChangesUrlCy,
                                       statePensionUrl,
                                       niSummaryUrl,
                                       niContributionsUrl,
                                       otherTaxesDigitalAssistantUrl,
                                       otherTaxesDigitalAssistantUrlCy,
                                       payeDigitalAssistantUrl,
                                       payeDigitalAssistantUrlCy,
                                       incomeTaxGeneralEnquiriesUrl,
                                       incomeTaxGeneralEnquiriesUrlCy,
                                       learnAboutCallChargesUrl,
                                       learnAboutCallChargesUrlCy,
                                       statePensionAgeUrl,
                                       tcNationalInsuranceRatesLettersUrl,
                                       tcNationalInsuranceRatesLettersUrlCy,
                                       tcPersonalAllowanceUrl,
                                       tcPersonalAllowanceUrlCy,
                                       scottishIncomeTaxUrl,
                                       scottishIncomeTaxUrlCy,
                                       cbTaxChargeUrl,
                                       cbTaxChargeUrlCy,
                                       selfAssessmentHelpAppealingPenaltiesUrl,
                                       selfAssessmentHelpAppealingPenaltiesUrlCy,
                                       addMissingTaxableIncomeUrl,
                                       helpToSaveGeneralEnquiriesUrl,
                                       helpToSaveGeneralEnquiriesUrlCy,
                                       helpToSaveDigitalAssistantUrl,
                                       selfAssessmentGeneralEnquiriesUrl,
                                       selfAssessmentGeneralEnquiriesUrlCy,
                                       simpleAssessmentGeneralEnquiriesUrl,
                                       simpleAssessmentGeneralEnquiriesUrlCy,
                                       cbGeneralEnquiriesUrl,
                                       cbGeneralEnquiriesUrlCy,
                                       taxCreditsGeneralEnquiriesUrl,
                                       taxCreditsGeneralEnquiriesUrlCy,
                                       otherTaxesGeneralEnquiriesUrl,
                                       otherTaxesGeneralEnquiriesUrlCy,
                                       findRepaymentPlanUrl,
                                       findRepaymentPlanUrlCy,
                                       pensionAnnualAllowanceUrl,
                                       pensionAnnualAllowanceUrlCy,
                                       childBenefitDigitalAssistantUrl,
                                       childBenefitDigitalAssistantUrlCy,
                                       incomeTaxDigitalAssistantUrl,
                                       incomeTaxDigitalAssistantUrlCy,
                                       selfAssessmentDigitalAssistantUrl,
                                       selfAssessmentDigitalAssistantUrlCy,
                                       taxCreditsDigitalAssistantUrl,
                                       taxCreditsDigitalAssistantUrlCy,
                                       tcStateBenefitsUrl,
                                       tcStateBenefitsUrlCy,
                                       tcCompanyBenefitsUrl,
                                       tcCompanyBenefitsUrlCy,
                                       niAppleWalletUrl,
                                       niGoogleWalletUrl,
                                       enableCustomerSatisfactionSurveys,
                                       findMyNinoAddToWallet,
                                       disableYourEmploymentIncomeChart,
                                       disableYourEmploymentIncomeChartAndroid,
                                       disableYourEmploymentIncomeChartIos,
                                       findMyNinoAddToGoogleWallet,
                                       disableOldTaxCalculator,
                                       useNudgeComm,
                                       enableChangeOfBankPegaURL,
                                       enableTaxCreditEndBanner)
