#%RAML 1.0
---

title: Mobile Startup
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/mobile-startup:
  /startup:
    get:
      displayName: Get startup data
      description: This endpoint retrieves the startup data that the mobile apps use to initialize themselves. The service
                   will use the authentication token to identify the NINO for the user that using the app. The json response
                   will contain keys for `helpToSave`, `taxCreditsRenewals` and `taxSummary`. The values for each of
                   these is the json returned from the relevant service. The response will also contain a `features`
                   key that references a set of feature flags.
      is: [headers.acceptHeader]
      (annotations.scope): "read:native-apps-api-orchestration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
      responses:
        200:
          body:
            application/json:
              examples:
                example-1:
                  value: !include examples/startup-example-1.json
